// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "SafeRoute API — сервис для построения безопасных маршрутов",
        "title": "SafeRoute API",
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "schemes": ["http"],
    "paths": {
        "/api/v1/critical": {
            "get": {
                "summary": "Получить безопасный маршрут с анализом аварийности",
                "description": "Запрашивает маршрут у 2GIS, получает погоду и рассчитывает опасность участков",
                "tags": ["routes"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "description": "JSON-запрос для API 2GIS",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routresponse.Query"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный анализ маршрута",
                        "schema": {
                            "$ref": "#/definitions/routresponse.RouteResponse"
                        }
                    },
                    "400": {"description": "Ошибка в данных запроса", "schema": {"type": "string"}},
                    "500": {"description": "Ошибка обработки маршрута или внешнего API", "schema": {"type": "string"}}
                }
            }
        }
    },
    "definitions": {}
}`

// SwaggerInfo хранит Swagger спецификацию
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SafeRoute API",
	Description:      "SafeRoute API — сервис для построения безопасных маршрутов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
